# -*- coding: utf-8 -*-
"""producto y suma

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdDqjQfuO_o7vlDabvU-ihK2pslqfqMN
"""

class Vector:
  def __init__(self, coordenada_x, coordenada_y, coordenada_z):
    self.x = coordenada_x
    self.y = coordenada_y
    self.z = coordenada_z
    self.magnitud = (self.x**2 + self.y**2 + self.z**2)**0.5
  def __str__(self):
    respuesta = "( "+str(self.x)+" , "+str(self.y)+" , "+str(self.z)+" )"
    return(respuesta)
  def productovectorial(self, seg):
    return(self.y*seg.z-seg.y*self.z, \
                         seg.x*self.z-self.x*seg.z,  \
                         self.x*seg.y-seg.x*self.y)
  def suma(self, seg):
    return(self.x+seg.x,self.y+seg.y,self.z+seg.z)

x_1 = float(input("ingrese coordenada x_1: "))
y_1 = float(input("ingrese coordenada y_1: "))
z_1 = float(input("ingrese coordenada z_1: "))


x_2 = float(input("ingrese coordenada x_2: "))
y_2 = float(input("ingrese coordenada y_2: "))
z_2 = float(input("ingrese coordenada z_2: "))

vec_10=Vector(x_1, y_1, z_1)
vec_20=Vector(x_2, y_2, z_2)
print("Fuerza del vector 1:", vec_10)
print("Fuerza del vector 2:", vec_20)
print("Modulo del vector 1:", vec_10.magnitud)
print("Modulo del vector 2:", vec_20.magnitud)
print("vector perpendicular a los dos vectores:", \
      vec_10.productovectorial(vec_20) )
print("Fuerza resultante entre los dos vectores:", vec_10.suma(vec_20))